"""
services/alert-manager/formatters/webhook.py

Formats alerts as JSON payloads for generic webhook delivery.
Compatible with Slack incoming webhooks, Discord, PagerDuty, etc.
"""

from datetime import datetime
from typing import Dict, Any
from shared.models import CorrelationCluster, Scenario, AlertTier


TIER_COLOR = {
    # These hex codes represent the colors that will appear on the left border 
    # of the Slack message attachment.
    AlertTier.WATCH:        "#FFA500",  # orange
    AlertTier.ALERT:        "#FF4500",  # red-orange
    AlertTier.INTELLIGENCE: "#FF0000",  # red
}


def format_correlation_slack(cluster: CorrelationCluster) -> Dict[str, Any]:
    """Slack-compatible attachment payload."""
    # WHAT'S FED IN: `cluster` is a CorrelationCluster object representing an alert. 
    # It contains all the context about the anomaly (rule triggered, description, tags).
    
    # We look up the tier color using .get(). If for some reason the tier isn't 
    # in our dictionary, it safely defaults to orange ("#FFA500").
    color = TIER_COLOR.get(cluster.alert_tier, "#FFA500")
    
    # HOW IT'S PROCESSED: We build a Python dictionary that perfectly matches 
    # Slack's required JSON schema for "Attachments" (richly formatted messages).
    return {
        "attachments": [
            {
                "color":    color,
                "title":    f"[{cluster.alert_tier.name}] {cluster.rule_name}",
                "text":     cluster.description,
                "fields": [
                    # BEST PRACTICE: Slicing lists ([:6], [:3]) prevents the Slack 
                    # message from becoming a massive wall of text if there are dozens 
                    # of tags or entities attached to this alert.
                    {"title": "Tags",       "value": ", ".join(cluster.tags[:6]),  "short": True},
                    {"title": "Entities",   "value": ", ".join(cluster.entity_ids[:3]), "short": True},
                    {"title": "Detected",   "value": cluster.detected_at.strftime("%Y-%m-%d %H:%M UTC"), "short": True},
                    {"title": "ID",         "value": cluster.correlation_id[:8],   "short": True},
                ],
                "footer": "SENTINEL",
                # TIP: Slack requires a UNIX timestamp (seconds since 1970) for the 'ts' field.
                "ts":     int(cluster.detected_at.timestamp()),
            }
        ]
    }


def format_scenario_slack(scenario: Scenario) -> Dict[str, Any]:
    """Slack-compatible scenario briefing."""
    # WHAT'S FED IN: `scenario` is a Scenario object. This is the AI-generated 
    # intelligence briefing created by Gemini in the reasoning service.
    
    # We start by defining the top-level fields for our Slack message.
    fields = [
        {"title": "Confidence",  "value": f"{scenario.confidence_overall}%", "short": True},
        {"title": "Status",      "value": scenario.status.value,             "short": True},
    ]
    
    # --- HOW THE LOOP WORKS ---
    # `scenario.hypotheses` is a list of Python dictionaries, where each dictionary
    # is a potential explanation (hypothesis) for the alert, generated by the AI.
    # We slice it `[:3]` so we only ever process a maximum of the top 3 hypotheses.
    for h in scenario.hypotheses[:3]:
        # During each iteration, 'h' is one hypothesis dictionary.
        # We extract its data and append a new Slack field dictionary to our list.
        # BEST PRACTICE: We use `h.get('key', 'default')` instead of `h['key']`.
        # Since the AI generated this data, there's a small chance a key might be missing.
        # `.get()` prevents the code from crashing with a KeyError if that happens.
        fields.append({
         "title": f"{h.get('label','?')} ({h.get('probability','?')}%)",
            "value": h.get("mechanism", "")[:150],
            "short": False,
        })
        
    # HOW IT'S PROCESSED: We assemble the final dictionary wrapping the `fields` list
    # we just built into the final Slack Attachment format.
    return {
        "attachments": [
            {
                "color":   "#0000FF",
                "title":   f"Intelligence: {scenario.headline}",
                "text":    scenario.significance,
                "fields":  fields,
                "footer":  "SENTINEL Reasoning",
                "ts":      int(scenario.created_at.timestamp()),
            }
        ]
    }


def format_generic(cluster: CorrelationCluster) -> Dict[str, Any]:
    """Generic JSON payload for any webhook endpoint."""
    # WHAT'S FED IN: The raw anomaly cluster object.
    # HOW IT'S PROCESSED: It extracts exactly what a standard 3rd-party webhook
    # (like an enterprise SIEM or ticketing system) would need and returns a simple dict.
    return {
        "sentinel_alert": {
            "correlation_id": cluster.correlation_id,
            "tier":           cluster.alert_tier.name,
            "tier_value":     cluster.alert_tier.value,
            "rule":           cluster.rule_name,
            "description":    cluster.description,
            "tags":           cluster.tags,
            "entity_ids":     cluster.entity_ids,
            # TIP: `.isoformat()` converts the Python datetime object into a 
            # standard, universal string format that JSON APIs can understand.
            "detected_at":    cluster.detected_at.isoformat(),
        }
    }