"""
services/reasoning/scenario_tracker.py
 
Monitors active scenarios for resolution signals.
 
Every 30 minutes:
  - Fetches all HYPOTHESIS and DEVELOPING scenarios from DB
  - For each scenario, checks if any watch or deny signals have appeared
  - Updates status and confidence accordingly
  - Confirms or denies based on threshold
 
Watch signal = specific observable event that would confirm a hypothesis.
Deny signal  = specific observable event that would refute it.
 
Both are plain-text descriptions generated by Claude.
We match them against recent events using keyword search on headlines
and named_entities. Not perfect — Phase 3 will use embedding similarity.
"""
 
import logging
from datetime import datetime, timedelta, timezone
from typing import List, Dict, Optional
 
from shared.db import get_timescale
from shared.models import ScenarioStatus
from .pattern_library import PatternLibrary
 
logger = logging.getLogger("reasoning.tracker")

CONFIRM_THRESHOLD = 80  # Confidence % above which we confirm a scenario
DENY_THRESHOLD = 15     # Confidence % below which we deny a scenario

class ScenarioTracker:
    def __init__(self):
        self._db = get_timescale()
        self._library = PatternLibrary()

    def check_all(self):
        active = self._fetch_active_scenarios()
        if not active:
            return
        
        logger.info(f"Checking {len(active)} active scenarios for resolution signals")
        for scenario in active:
            # CODING CONVICTION: Defensive Programming in Batch Processes.
            # We wrap the inner loop in a try-except block so that if one scenario 
            # fails (e.g., due to bad JSON or a weird DB edge case), it doesn't 
            # crash the entire tracker and stop the other scenarios from being checked.
            try:
                self._check_scenario(scenario)
            except Exception as e:
                logger.error(f"Error checking scenario {scenario.scenario_id}: {e}")
                
    def _check_scenario(self, scenario: Dict):
        scenario_id = str(scenario["scenario_id"])
        hypotheses  = scenario.get("hypotheses") or []
        confidence  = int(scenario.get("confidence_overall") or 50)
 
        # Collect all watch and deny signals across hypotheses
        watch_signals = []
        deny_signals  = []

        for h in hypotheses:
            watch_signals.extend(h.get("watch_signals") or [])
            deny_signals.extend(h.get("deny_signals") or [])
        
        watch_hits = self._match_signals(watch_signals)
        deny_hits  = self._match_signals(deny_signals)

        new_confidence = confidence
        # FIXED: Typo 'statud_change' changed to 'status_change'. 
        # Before, if watch_hits was false but deny_hits was true, it would throw an UnboundLocalError.
        status_change = None
        notes = []

        if watch_hits:
            # CRITICAL THINKING: Bounded adjustments.
            # We limit the "bump" to a maximum of 30 points regardless of how many 
            # watch signals hit. This prevents a single noisy event from artificially 
            # skyrocketing our confidence to 100% instantly.
            bump = min(15 * len(watch_hits), 30)  # Cap max bump to prevent overconfidence
            new_confidence = min(100, confidence + bump) # Increase confidence by 15% per watch hit, up to 30%
            notes.append(f"Watch signals hit: {watch_hits[:3]}")
            if new_confidence >= CONFIRM_THRESHOLD:
                status_change = ScenarioStatus.CONFIRMED

        if deny_hits:
            # CRITICAL THINKING: Asymmetric penalization.
            # Notice the drop maxes out at 40, while the bump maxes out at 30. 
            # In intelligence, disproving evidence is often weighted slightly heavier 
            # than confirming evidence to avoid confirmation bias.
            drop = min(20 * len(deny_hits), 40) # Cap max drop to prevent over-pessimism
            new_confidence = max(0, new_confidence - drop) # Decrease confidence by 20% per deny hit, up to 40%
            notes.append(f"Deny signals hit: {deny_hits[:3]}") 
            if new_confidence <= DENY_THRESHOLD:
                status_change = ScenarioStatus.DENIED

        if new_confidence != confidence or status_change:
            self._update_scenario(
                scenario_id, 
                new_confidence, 
                status_change, 
                "; ".join(notes)
            )
            logger.info(
                f"Scenario {scenario_id[:8]}: "
                f"confidence {confidence}→{new_confidence} "
                f"{'→ ' + status_change.value if status_change else ''}"
            )
 
            if status_change in (ScenarioStatus.CONFIRMED, ScenarioStatus.DENIED):
                self._library.record_outcome(
                    scenario_id,
                    status_change.value,
                    "; ".join(notes),
                ) # FIXED: Added missing closing parenthesis

    def _match_signals(self, signals: List[str]) -> List[str]:
        """
        Check if any signals have appeared in recent events.
        Simple keyword match on headlines and named_entities.
        Returns list of signals that found matches.
        """
        if not signals:
            return []
        
        matched = []
        cutoff = datetime.now(timezone.utc) - timedelta(hours = 48)  # Look back 48 hours
        
        # CRITICAL THINKING: Resource constraints.
        # Querying text inside a database loop is an "N+1 query" anti-pattern and can 
        # exhaust database resources. We slice `signals[:10]` to strictly limit the 
        # maximum number of database queries executed per scenario.
        for signal in signals[:10]:  # Check up to 10 signals to limit DB load
            keywords = [w.lower() for w in signal.split() if len(w) > 4]  # keywords extracted by splitting signal text
            if not keywords:
                continue    

            try:
                # CRITICAL THINKING: Existence checks over Counting.
                # We only need to know IF a signal happened, not HOW MANY times.
                # Using `LIMIT 1` tells the database to stop searching the moment it 
                # finds a single match, making this query significantly faster.
                for keyword in keywords[:3]: # Limit to top 3 keywords per signal for efficiency
                    rows = self._db.query("""
                        SELECT COUNT(*) as cnt FROM events
                        WHERE occurred_at > %s
                          AND (
                            LOWER(headline) LIKE %s
                            OR %s = ANY(ARRAY(SELECT LOWER(e) FROM unnest(named_entities) e))
                          )
                        LIMIT 1
                    """, (cutoff, f"%{keyword}%", keyword)) # Match keyword in headline (using LIKE) or exact match in named_entities (using ANY)
                    
                    if rows and rows[0].get("cnt", 0) > 0: # If we found any event matching this keyword, consider the signal "hit"
                        matched.append(signal) # Record the original signal text, not just the keyword, for better traceability
                        break
            except Exception as e:
                logger.debug(f"Signal match error: {e}")
 
        return matched
    
    def _fetch_active_scenarios(self) -> List[Dict]:
        try:
            return self._db.query("""
                SELECT scenario_id, headline, status, confidence_overall,
                       hypotheses, created_at, updated_at
                FROM scenarios
                WHERE status IN ('hypothesis', 'developing')
                  AND created_at > NOW() - INTERVAL '30 days'
                ORDER BY confidence_overall DESC
                LIMIT 100
            """)
        except Exception as e:
            logger.error(f"fetch_active_scenarios failed: {e}")
            return []
 
    def _update_scenario(
        self,
        scenario_id:    str,
        new_confidence: int,
        new_status:     Optional[ScenarioStatus],
        notes:          str,
    ):
        # CODING CONVICTION: Audit Trails.
        # We append to a `confidence_history` JSONB array instead of just overwriting 
        # the confidence. This allows human analysts to trace exactly *when* and *why* 
        # an AI decided to upgrade or downgrade a scenario's likelihood.
        try:
            if new_status:
                self._db.execute("""
                    UPDATE scenarios
                    SET confidence_overall = %s,
                        status            = %s,
                        updated_at        = NOW(),
                        confidence_history = confidence_history || %s::jsonb
                    WHERE scenario_id = %s
                """, (
                    new_confidence,
                    new_status.value,
                    f'[{{"ts":"{datetime.now(timezone.utc).isoformat()}",'
                    f'"confidence":{new_confidence},"notes":"{notes}"}}]',
                    scenario_id,
                ))
            else:
                self._db.execute("""
                    UPDATE scenarios
                    SET confidence_overall = %s,
                        status            = CASE
                            WHEN status = 'hypothesis' AND %s >= 60 THEN 'developing'
                            ELSE status
                        END,
                        updated_at        = NOW(),
                        confidence_history = confidence_history || %s::jsonb
                    WHERE scenario_id = %s
                """, (
                    new_confidence,
                    new_confidence,
                    f'[{{"ts":"{datetime.now(timezone.utc).isoformat()}",'
                    f'"confidence":{new_confidence},"notes":"{notes}"}}]',
                    scenario_id,
                ))
        except Exception as e:
            logger.error(f"update_scenario failed ({scenario_id}): {e}")
            