"""
services/reasoning/scenario_tracker.py
 
Monitors active scenarios for resolution signals.
 
Every 30 minutes:
  - Fetches all HYPOTHESIS and DEVELOPING scenarios from DB
  - For each scenario, checks if any watch or deny signals have appeared
  - Updates status and confidence accordingly
  - Confirms or denies based on threshold
 
Watch signal = specific observable event that would confirm a hypothesis.
Deny signal  = specific observable event that would refute it.
 
Both are plain-text descriptions generated by Claude.
We match them against recent events using keyword search on headlines
and named_entities. Not perfect — Phase 3 will use embedding similarity.
"""
 
import json
import logging
from datetime import datetime, timedelta, timezone
from typing import List, Dict, Optional, Tuple
 
from shared.db import get_timescale, get_redis
from shared.models import ScenarioStatus
from shared.kafka import SentinelProducer, Topics
from shared.utils.source_scorecard import update_source_scorecard
from .pattern_library import PatternLibrary
 
logger = logging.getLogger("reasoning.tracker")

from .calibration_harness import DynamicBayesianCalibrator

CONFIRM_THRESHOLD = 65  # Confidence % above which we confirm a scenario
DENY_THRESHOLD = 25     # Confidence % below which we deny a scenario

# ── EXPIRY DECAY ─────────────────────────────────────────────────────────────
#
# A forecast that did not happen is wrong, and nothing here was saying so.
#
# Confidence moved only when a signal matched: a watch hit raised it, a deny hit
# lowered it. But the ordinary way a scenario is wrong is that the thing it
# predicted simply never occurs -- no deny signal fires, because nothing
# happened at all. Absence of the predicted event moved the number not at all.
#
# Measured over the corpus: 723 scenarios, 219 confirmed, 0 denied, and the
# lowest confidence ever recorded was 34 against a deny threshold of 25. The
# threshold was unreachable, so the confirm/deny loop was a confirm loop, and
# every calibration statistic derived from it -- the pattern library's outcome
# records, the Brier scores, the source scorecards -- was computed over a
# population from which the losses had been silently excluded.
#
# Decay is what makes DENY_THRESHOLD reachable. Past its own stated horizon, a
# scenario whose watch signals have not fired loses confidence per elapsed
# horizon, so a prediction that never came true eventually resolves as denied
# instead of sitting at "hypothesis" indefinitely -- the oldest was ten days old
# and still open.
SCENARIO_HORIZON_HOURS = {
    "immediate": 6,
    "24h": 24,
    "72h": 72,
    "1week": 168,
    "1month": 720,
}

# Used when a scenario states no horizon, or states one that is not recognised.
DEFAULT_HORIZON_HOURS = 72

# Confidence points lost per horizon elapsed without the predicted signals
# firing. At 12 a 50-point scenario reaches the deny threshold after roughly two
# unfulfilled horizons, which is a fair hearing rather than a hair trigger.
EXPIRY_DECAY_PER_HORIZON = 12

# Decay never starts before the horizon the scenario itself claimed. A 1-month
# forecast is not wrong on day two.
EXPIRY_GRACE_HORIZONS = 1.0

def _signal_parts(signal) -> tuple:
    """(entity, text) from either shape a signal can arrive in.

    Structured signals are what the generator emits now: an entity, an
    observable, and optionally a comparator and threshold. Everything already
    stored is a bare sentence, and those keep working -- with no entity, which
    is exactly why they resolve so rarely.
    """
    # The observable is returned empty rather than falling back to the entity.
    # Substituting it made the entity its own keyword, so the query demanded
    # `headline ILIKE '%ethusdt%' AND primary_entity_id = 'ETHUSDT'` -- the same
    # fact twice, rejecting events correctly attributed to the entity whose
    # headline happens not to spell it.
    if isinstance(signal, dict):
        return (str(signal.get("entity") or "").strip(),
                str(signal.get("observable") or "").strip())
    entity = getattr(signal, "entity", None)
    if entity is not None:
        return (str(entity).strip(),
                str(getattr(signal, "observable", "") or "").strip())
    return "", str(signal or "")


def _checkable(signals) -> list:
    """The subset of signals that name something to look for.

    Returns everything when nothing is structured, so a scenario written before
    ResolutionSignal existed still gets its keyword pass rather than silently
    becoming unresolvable. It is only when a hypothesis has *some* named signals
    that the unnamed ones are dropped -- there, the named ones are strictly
    better evidence and the sentences only add noise.
    """
    named = [s for s in signals if _signal_parts(s)[0]]
    return named or list(signals)


def _as_datetime(value) -> Optional[datetime]:
    """A timezone-aware datetime from whatever the row actually carried.

    This was `if not isinstance(created, datetime): return 0, ""`, written as a
    defensive guard and behaving as an off switch: the database client returns
    `created_at` as a **string**, so every call returned zero and the expiry
    decay -- the mechanism that makes denial reachable at all -- did nothing
    from the moment it was deployed. Verified in the running container:
    `created_at type: str`. The tracker sweep examined a hundred scenarios aged
    between 113 and 272 hours, every one of them overdue, and updated none.
    Scenario status stayed at 219 confirmed and 0 denied.

    The logic had been driven against a synthetic datetime and never against the
    type production supplies. Accepting both is the fix; returning None only
    when the value genuinely cannot be read is what keeps the guard defensive
    without letting it be silent.
    """
    if value is None:
        return None
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=timezone.utc)
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        # Postgres renders UTC as "+00" and ISO-8601 as "Z"; fromisoformat on
        # this runtime accepts neither without help.
        if text.endswith("Z"):
            text = text[:-1] + "+00:00"
        elif len(text) > 3 and text[-3] in "+-" and ":" not in text[-3:]:
            text = text + ":00"
        try:
            parsed = datetime.fromisoformat(text)
        except ValueError:
            logger.debug("Could not read a timestamp from %r; no decay applied.", value)
            return None
        return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)
    return None


def _horizon_hours(hypotheses) -> int:
    """The longest horizon any of this scenario's hypotheses claimed.

    The longest, not the shortest: a scenario is not overdue until every branch
    of it is.
    """
    hours = 0
    for h in (hypotheses or []):
        if not isinstance(h, dict):
            continue
        raw = str(h.get("time_horizon") or "").strip().lower()
        hours = max(hours, SCENARIO_HORIZON_HOURS.get(raw, 0))
    return hours or DEFAULT_HORIZON_HOURS


def _expiry_decay(scenario: Dict, hypotheses, now: datetime) -> Tuple[int, str]:
    """Confidence lost to a horizon that passed without the predicted signals.

    Returns (points, note). Zero and an empty note while the scenario is still
    within the time it gave itself.
    """
    created = _as_datetime(scenario.get("created_at"))
    if created is None:
        return 0, ""

    horizon = _horizon_hours(hypotheses)
    elapsed_hours = (now - created).total_seconds() / 3600.0
    horizons_elapsed = elapsed_hours / max(1.0, float(horizon))

    overdue = horizons_elapsed - EXPIRY_GRACE_HORIZONS
    if overdue <= 0:
        return 0, ""

    points = int(round(overdue * EXPIRY_DECAY_PER_HORIZON))
    if points <= 0:
        return 0, ""
    return points, (
        f"No predicted signal in {elapsed_hours:.0f}h against a stated "
        f"{horizon}h horizon ({horizons_elapsed:.1f} horizons); "
        f"-{points} for an unfulfilled forecast"
    )



class ScenarioTracker:
    def __init__(self, db, producer=None, redis=None):
        self._db = db
        self._library = PatternLibrary(db)
        self._producer = producer
        self._redis = redis

    async def check_all(self):
        active = await self._fetch_active_scenarios()
        if not active:
            return
        
        logger.info(f"Checking {len(active)} active scenarios for resolution signals")
        for scenario in active:
            try:
                await self._check_scenario(scenario)
            except Exception as e:
                logger.error(f"Error checking scenario {scenario.scenario_id}: {e}")
                
    async def _check_scenario(self, scenario: Dict):
        scenario_id = str(scenario["scenario_id"])
        hypotheses  = scenario.get("hypotheses") or []
        original_confidence = int(scenario.get("confidence_overall") or 50)
        confidence = original_confidence

        watch_hits_by_index = {}
        deny_hits_by_index = {}
        notes = []

        for idx, h in enumerate(hypotheses):
            w_sigs = h.get("watch_signals") or []
            d_sigs = h.get("deny_signals") or []

            # Only signals that can actually be looked up count as evidence.
            #
            # A signal with no entity is a sentence, and a sentence that fails
            # to match is not evidence of absence -- it is evidence that nobody
            # said what to look for. Feeding those into the recalibrator as
            # misses is the same conflation that caused the original defect
            # here: a query that could not run and a signal that genuinely did
            # not fire produced identical silence.
            #
            # Several hundred scenarios were generated before ResolutionSignal
            # existed and their signals have no entity. They stay unresolved,
            # which is honest, rather than accumulating false negatives against
            # hypotheses nobody can check.
            w_checkable = _checkable(w_sigs)
            d_checkable = _checkable(d_sigs)

            w_hits = await self._match_signals(w_checkable) if w_checkable else []
            if w_hits:
                watch_hits_by_index[idx] = w_hits

            d_hits = await self._match_signals(d_checkable) if d_checkable else []
            if d_hits:
                deny_hits_by_index[idx] = d_hits

        status_change = None

        # An overdue forecast loses confidence whether or not anything fired.
        # Applied only when no watch signal hit on this pass: a scenario that is
        # still producing confirming evidence is not overdue, it is running late.
        decay_note = ""
        if not watch_hits_by_index:
            decay, decay_note = _expiry_decay(
                scenario, hypotheses, datetime.now(timezone.utc)
            )
            if decay:
                confidence = max(0, confidence - decay)
                notes.append(decay_note)
                if confidence <= DENY_THRESHOLD:
                    status_change = ScenarioStatus.DENIED

        if watch_hits_by_index or deny_hits_by_index:
            updated_hypotheses, confidence, bayes_notes = DynamicBayesianCalibrator.recalibrate_hypotheses(
                hypotheses, watch_hits_by_index, deny_hits_by_index
            )
            hypotheses = updated_hypotheses
            notes.append(bayes_notes)

            if confidence >= CONFIRM_THRESHOLD:
                status_change = ScenarioStatus.CONFIRMED
            elif confidence <= DENY_THRESHOLD:
                status_change = ScenarioStatus.DENIED

        if (
            confidence != original_confidence
            or status_change
            or watch_hits_by_index
            or deny_hits_by_index
            or decay_note
        ):
            await self._update_scenario(
                scenario_id, 
                confidence, 
                status_change, 
                "; ".join(notes),
                hypotheses=hypotheses
            )
            logger.info(
                f"Scenario {scenario_id[:8]}: "
                f"confidence {original_confidence}→{confidence} "
                f"{'→ ' + status_change.value if status_change else ''}"
            )
 
            if status_change in (ScenarioStatus.CONFIRMED, ScenarioStatus.DENIED):
                await self._library.record_outcome(
                    scenario_id,
                    status_change.value,
                    "; ".join(notes),
                )
                try:
                    sources = await self._get_scenario_event_sources(scenario_id)
                    redis_client = self._redis or (await get_redis())
                    if sources and redis_client:
                        story_confirmed = (status_change == ScenarioStatus.CONFIRMED)
                        conviction_float = float(confidence) / 100.0 if confidence > 1.0 else float(confidence)
                        for src in sources:
                            await update_source_scorecard(redis_client, src, story_confirmed, conviction_float)
                except Exception as e:
                    logger.error(f"Failed to update source scorecard for scenario {scenario_id}: {e}")
                
            if status_change == ScenarioStatus.DENIED and self._producer:
                try:
                    # Fetch the rule_id that created this scenario's cluster
                    rows = await self._db.query("""
                        SELECT c.rule_id 
                        FROM scenarios s
                        JOIN correlations c ON s.correlation_id = c.correlation_id
                        WHERE s.scenario_id = $1
                    """, scenario_id)
                    
                    if rows and rows[0].get("rule_id"):
                        rule_id = rows[0]["rule_id"]
                        if rule_id.startswith("syn_") or rule_id.startswith("rule_"):
                            await self._producer.send(Topics.RULES_FEEDBACK, {
                                "type": "rule_failure",
                                "rule_id": rule_id,
                                "scenario_id": scenario_id,
                                "reason": f"Scenario denied. {'; '.join(notes)}"
                            })
                            logger.info(f"Published rule_failure feedback for rule {rule_id}")
                except Exception as e:
                    logger.error(f"Failed to publish rule feedback: {e}")

    async def _match_signals(self, signals: List[str]) -> List[str]:
        """
        Check if any signals have appeared in recent events.
        Simple keyword match on headlines and named_entities.
        Returns list of signals that found matches.
        """
        if not signals:
            return []
        
        matched = []
        cutoff = datetime.now(timezone.utc) - timedelta(hours = 48)  # Look back 48 hours
        
        # CRITICAL THINKING: Resource constraints.
        # Querying text inside a database loop is an "N+1 query" anti-pattern and can 
        # exhaust database resources. We slice `signals[:10]` to strictly limit the 
        # maximum number of database queries executed per scenario.
        # ALL, not ANY -- and the difference is the whole meaning of the result.
        #
        # Once the cast above was fixed and matching actually ran, the tracker
        # confirmed 185 scenarios and denied none. Measured over 303 distinct
        # watch signals against 48 hours of events:
        #
        #     any keyword matches   271 / 303   (89%)
        #     all keywords match      7 / 303   (2.3%)
        #
        # A rule that fires on 89% of signals is not evidence, it is a rubber
        # stamp: the same wording appears in a scenario's watch signals and its
        # deny signals, both hit, and the Bayesian recalibrator nets out
        # positive on noise. Dropping corpus-common words first barely moves it
        # (87%), because the frequency is in the corpus rather than the
        # vocabulary -- "wallet" and "watched" each appear in 59,063 headlines
        # of position telemetry.
        #
        # Worth stating plainly, because this fix is necessary and not
        # sufficient: at 2.3% the signals are still not really checkable. They
        # are model-generated prose -- "Significant price movements on
        # cryptocurrency exchanges" -- which matches everything under ANY and
        # nothing under ALL. The generator needs to emit signals with a named
        # entity and a threshold before resolution means much. Until it does,
        # under-resolving is the honest failure and over-confirming is not:
        # these outcomes feed the confidence calibration and the pattern
        # library, so a false confirmation is worse than no confirmation.
        for signal in signals[:10]:  # Check up to 10 signals to limit DB load
            entity, text = _signal_parts(signal)
            keywords = [w.lower() for w in text.split() if len(w) > 4][:3]

            # A named entity is checkable on its own. The keyword guard below
            # predates the entity path, and skipping here threw away signals
            # like {"entity": "NVDA", "observable": "price up"} -- every word
            # four characters or shorter, so no keywords, so never looked up at
            # all despite naming an indexed entity.
            if not keywords and not entity:
                continue

            # A named entity turns a keyword search into a lookup. Signals
            # generated from now on carry one because ResolutionSignal requires
            # it; the ones already in the table are plain strings and do not,
            # so both shapes have to work -- there are hundreds of stored
            # scenarios and rewriting their hypotheses would be inventing
            # entities they never named.
            if entity:
                rows = await self._match_on_entity(entity, keywords, cutoff)
                if rows:
                    matched.append(text)
                continue

            try:
                # `events.tags` and `events.named_entities` are text[], and this
                # cast said varchar[]. Postgres has no `text[] && varchar[]`
                # operator, so the statement raised every time it ran -- caught
                # below and logged at debug, which is why nothing showed at INFO.
                #
                # _match_signals therefore returned [] for every signal of every
                # scenario since the tracker was written. Nothing could ever
                # confirm or deny, and all 231 scenarios sat at `hypothesis`
                # while the loop reported "Checking 100 active scenarios" every
                # thirty minutes. The confidence numbers this system produces
                # have never once been scored against an outcome.
                rows = await self._db.query("""
                    SELECT 1 FROM events
                    WHERE occurred_at > $1
                      AND (
                        headline ILIKE ALL($2)
                        OR tags @> $3::text[]
                        OR named_entities @> $4::text[]
                      )
                    LIMIT 1
                """, 
                    cutoff, 
                    [f"%{k}%" for k in keywords], # ILIKE ANY mapping
                    keywords,                     # tags && array
                    keywords                      # named_entities && array
                )
                
                if rows: 
                    matched.append(signal) 
            except Exception as e:
                # Not debug. A query that cannot execute is not a signal that
                # did not match, and the two were indistinguishable here for the
                # lifetime of the service.
                logger.warning("Signal match query failed for %r: %s", signal[:60], e)
 
        return matched
    
    async def _match_on_entity(self, entity: str, keywords: list, cutoff) -> list:
        """Events about a named entity, narrowed by the observable's words.

        Keyed on primary_entity_id rather than scanning headlines, so this is an
        index lookup instead of a text match across the whole window. The
        keywords still have to all appear, for the reason given above -- naming
        the entity removes the ambiguity about *what* the signal is about, not
        about whether the thing described actually happened.
        """
        try:
            return await self._db.query("""
                SELECT 1 FROM events
                WHERE occurred_at > $1
                  AND (upper(primary_entity_id) = upper($2)
                       OR upper(primary_entity_name) = upper($2))
                  AND (
                    $5::boolean
                    OR headline ILIKE ALL($3)
                    OR tags @> $4::text[]
                    OR named_entities @> $4::text[]
                  )
                LIMIT 1
            """, cutoff, entity, [f"%{k}%" for k in keywords] or [""], keywords, not keywords)
        except Exception as e:
            logger.warning("Entity signal match failed for %r: %s", entity[:40], e)
            return []

    async def _fetch_active_scenarios(self) -> List[Dict]:
        """The open scenarios due for evaluation, least recently touched first.

        This was ORDER BY confidence_overall DESC, which made the window a
        one-way door. Being evaluated lowers confidence; lower confidence falls
        out of a window ordered by confidence; and outside the window a scenario
        is never evaluated again. Measured against 494 open scenarios: of the
        top 100, not one had ever been revisited, while 111 of the other 394
        had -- and those averaged 66.1 confidence against the window's 85.8. The
        scenarios that had started to look doubtful were exactly the ones the
        ordering removed from the process that would have refuted them.

        Ordering by staleness sweeps the whole corpus round-robin: evaluating a
        scenario sets updated_at, which sends it to the back of the queue, so
        every open scenario is reached regardless of what its confidence does.
        """
        try:
            return await self._db.query("""
                SELECT scenario_id, headline, status, confidence_overall,
                       hypotheses, created_at, updated_at
                FROM scenarios
                WHERE status IN ('hypothesis', 'developing')
                  AND created_at > NOW() - INTERVAL '30 days'
                ORDER BY updated_at ASC NULLS FIRST
                LIMIT 100
            """)
        except Exception as e:
            logger.error(f"fetch_active_scenarios failed: {e}")
            return []
 
    async def _update_scenario(
        self,
        scenario_id:    str,
        new_confidence: int,
        new_status:     Optional[ScenarioStatus],
        notes:          str,
        hypotheses:     Optional[List[Dict]] = None,
    ):
        try:
            # The objects themselves, not json.dumps(...) of them.
            #
            # The pool registers a jsonb codec whose encoder is already
            # json.dumps (shared/db/__init__.py), so a pre-serialised string is
            # encoded a second time. The insert path in reasoning/main.py was
            # corrected for exactly this; these two writes were missed because
            # they carry an explicit ::jsonb cast, which looks like it settles
            # the question and does not.
            #
            # What it cost: every appended confidence_history entry landed as a
            # JSON *string* inside the array rather than an object, so
            # `entry->>'confidence'` returned null on all 672 scenarios. The
            # tracker computes watch/deny hits and Bayesian confidence updates
            # and then wrote them where nothing could read them back -- the
            # learning loop recorded its results in a form it cannot itself
            # consume. Measured live: hypotheses came back as jsonb "string" on
            # 324 of 672 rows, and confidence_history on every row that had one.
            history_entry = [{
                "ts": datetime.now(timezone.utc).isoformat(),
                "confidence": new_confidence,
                "notes": notes
            }]

            hyp_json = hypotheses if hypotheses else None

            if new_status:
                if hyp_json:
                    await self._db.execute("""
                        UPDATE scenarios
                        SET confidence_overall = $1,
                            status            = $2,
                            hypotheses        = $3::jsonb,
                            updated_at        = NOW(),
                            confidence_history = confidence_history || $4::jsonb
                        WHERE scenario_id = $5
                    """, new_confidence, new_status.value, hyp_json, history_entry, scenario_id)
                else:
                    await self._db.execute("""
                        UPDATE scenarios
                        SET confidence_overall = $1,
                            status            = $2,
                            updated_at        = NOW(),
                            confidence_history = confidence_history || $3::jsonb
                        WHERE scenario_id = $4
                    """, new_confidence, new_status.value, history_entry, scenario_id)
            else:
                if hyp_json:
                    await self._db.execute("""
                        UPDATE scenarios
                        SET confidence_overall = $1,
                            hypotheses        = $2::jsonb,
                            status            = CASE
                                WHEN status = 'hypothesis' AND $1 >= 60 THEN 'developing'
                                ELSE status
                            END,
                            updated_at        = NOW(),
                            confidence_history = confidence_history || $3::jsonb
                        WHERE scenario_id = $4
                    """, new_confidence, hyp_json, history_entry, scenario_id)
                else:
                    await self._db.execute("""
                        UPDATE scenarios
                        SET confidence_overall = $1,
                            status            = CASE
                                WHEN status = 'hypothesis' AND $1 >= 60 THEN 'developing'
                                ELSE status
                            END,
                            updated_at        = NOW(),
                            confidence_history = confidence_history || $2::jsonb
                        WHERE scenario_id = $3
                    """, new_confidence, history_entry, scenario_id)
        except Exception as e:
            logger.error(f"update_scenario failed ({scenario_id}): {e}")

    async def _get_scenario_event_sources(self, scenario_id: str) -> List[str]:
        """
        Finds distinct event sources originating/supporting a scenario.
        """
        try:
            rows = await self._db.query("""
                SELECT DISTINCT e.source
                FROM scenarios s
                LEFT JOIN correlations c ON s.correlation_id = c.correlation_id
                JOIN events e ON (
                    (c.trigger_event_id IS NOT NULL AND e.event_id = c.trigger_event_id)
                    OR (c.supporting_event_ids IS NOT NULL AND e.event_id = ANY(c.supporting_event_ids))
                    OR (s.supporting_event_ids IS NOT NULL AND e.event_id = ANY(s.supporting_event_ids))
                )
                WHERE s.scenario_id::text = $1::text AND e.source IS NOT NULL AND e.source != ''
            """, scenario_id)
            return [r["source"] for r in rows if r.get("source")]
        except Exception as e:
            logger.error(f"Failed to query scenario event sources ({scenario_id}): {e}")
            return []


            