"""
services/reasoning/scenario_tracker.py
 
Monitors active scenarios for resolution signals.
 
Every 30 minutes:
  - Fetches all HYPOTHESIS and DEVELOPING scenarios from DB
  - For each scenario, checks if any watch or deny signals have appeared
  - Updates status and confidence accordingly
  - Confirms or denies based on threshold
 
Watch signal = specific observable event that would confirm a hypothesis.
Deny signal  = specific observable event that would refute it.
 
Both are plain-text descriptions generated by Claude.
We match them against recent events using keyword search on headlines
and named_entities. Not perfect — Phase 3 will use embedding similarity.
"""
 
import logging
from datetime import datetime, timedelta, timezone
from typing import List, Dict, Optional
 
from shared.db import get_timescale
from shared.models import ScenarioStatus
from shared.kafka import SentinelProducer, Topics
from .pattern_library import PatternLibrary
 
logger = logging.getLogger("reasoning.tracker")

CONFIRM_THRESHOLD = 80  # Confidence % above which we confirm a scenario
DENY_THRESHOLD = 15     # Confidence % below which we deny a scenario

class ScenarioTracker:
    def __init__(self, db, producer=None):
        self._db = db
        self._library = PatternLibrary(db)
        self._producer = producer

    async def check_all(self):
        active = await self._fetch_active_scenarios()
        if not active:
            return
        
        logger.info(f"Checking {len(active)} active scenarios for resolution signals")
        for scenario in active:
            # CODING CONVICTION: Defensive Programming in Batch Processes.
            # We wrap the inner loop in a try-except block so that if one scenario 
            # fails (e.g., due to bad JSON or a weird DB edge case), it doesn't 
            # crash the entire tracker and stop the other scenarios from being checked.
            try:
                await self._check_scenario(scenario)
            except Exception as e:
                logger.error(f"Error checking scenario {scenario.scenario_id}: {e}")
                
    async def _check_scenario(self, scenario: Dict):
        scenario_id = str(scenario["scenario_id"])
        hypotheses  = scenario.get("hypotheses") or []
        original_confidence = int(scenario.get("confidence_overall") or 50)
        confidence = original_confidence
 
        # Collect all watch and deny signals across hypotheses
        watch_signals = []
        deny_signals  = []

        for h in hypotheses:
            watch_signals.extend(h.get("watch_signals") or [])
            deny_signals.extend(h.get("deny_signals") or [])
        
        # FIXED: Typo 'statud_change' changed to 'status_change'. 
        # Before, if watch_hits was false but deny_hits was true, it would throw an UnboundLocalError.
        status_change = None
        notes = []

        if watch_signals:
            # CRITICAL THINKING: Bounded adjustments.
            # We limit the "bump" to a maximum of 30 points regardless of how many 
            # watch signals hit. This prevents a single noisy event from artificially 
            # skyrocketing our confidence to 100% instantly.
            watch_hits = await self._match_signals(watch_signals)
            if watch_hits:
                bump = min(15 * len(watch_hits), 30)  # Cap max bump to prevent overconfidence
                confidence = min(100, confidence + bump) # Increase confidence by 15% per watch hit, up to 30%
                notes.append(f"Watch signals hit: {watch_hits[:3]}")
                if confidence >= CONFIRM_THRESHOLD:
                    status_change = ScenarioStatus.CONFIRMED

        if deny_signals:
            # CRITICAL THINKING: Asymmetric penalization.
            # Notice the drop maxes out at 40, while the bump maxes out at 30. 
            # In intelligence, disproving evidence is often weighted slightly heavier 
            # than confirming evidence to avoid confirmation bias.
            deny_hits = await self._match_signals(deny_signals)
            if deny_hits:
                drop = min(20 * len(deny_hits), 40) # Cap max drop to prevent over-pessimism
                confidence = max(0, confidence - drop) # Decrease confidence by 20% per deny hit, up to 40%
                notes.append(f"Deny signals hit: {deny_hits[:3]}") 
                if confidence <= DENY_THRESHOLD:
                    status_change = ScenarioStatus.DENIED

        if confidence != original_confidence or status_change:
            await self._update_scenario(
                scenario_id, 
                confidence, 
                status_change, 
                "; ".join(notes)
            )
            logger.info(
                f"Scenario {scenario_id[:8]}: "
                f"confidence {confidence}→{new_confidence} "
                f"{'→ ' + status_change.value if status_change else ''}"
            )
 
            if status_change in (ScenarioStatus.CONFIRMED, ScenarioStatus.DENIED):
                await self._library.record_outcome(
                    scenario_id,
                    status_change.value,
                    "; ".join(notes),
                ) # FIXED: Added missing closing parenthesis
                
            if status_change == ScenarioStatus.DENIED and self._producer:
                try:
                    # Fetch the rule_id that created this scenario's cluster
                    rows = await self._db.query("""
                        SELECT c.rule_id 
                        FROM scenarios s
                        JOIN correlation_clusters c ON s.correlation_id = c.correlation_id
                        WHERE s.scenario_id = $1
                    """, scenario_id)
                    
                    if rows and rows[0].get("rule_id"):
                        rule_id = rows[0]["rule_id"]
                        if rule_id.startswith("syn_") or rule_id.startswith("rule_"):
                            await self._producer.send(Topics.RULES_FEEDBACK, {
                                "type": "rule_failure",
                                "rule_id": rule_id,
                                "scenario_id": scenario_id,
                                "reason": f"Scenario denied. {'; '.join(notes)}"
                            })
                            logger.info(f"Published rule_failure feedback for rule {rule_id}")
                except Exception as e:
                    logger.error(f"Failed to publish rule feedback: {e}")

    async def _match_signals(self, signals: List[str]) -> List[str]:
        """
        Check if any signals have appeared in recent events.
        Simple keyword match on headlines and named_entities.
        Returns list of signals that found matches.
        """
        if not signals:
            return []
        
        matched = []
        cutoff = datetime.now(timezone.utc) - timedelta(hours = 48)  # Look back 48 hours
        
        # CRITICAL THINKING: Resource constraints.
        # Querying text inside a database loop is an "N+1 query" anti-pattern and can 
        # exhaust database resources. We slice `signals[:10]` to strictly limit the 
        # maximum number of database queries executed per scenario.
        for signal in signals[:10]:  # Check up to 10 signals to limit DB load
            keywords = [w.lower() for w in signal.split() if len(w) > 4][:3]  # keywords extracted by splitting signal text
            if not keywords:
                continue    

            try:
                # ARCHITECTURAL FIX: Native Postgres Array overlap operator (&&)
                # Replaced expensive unnest() scans with optimized index-friendly arrays.
                # Passed the keywords as a native tuple to leverage psycopg2 array adaptation.
                rows = await self._db.query("""
                    SELECT 1 FROM events
                    WHERE occurred_at > $1
                      AND (
                        headline ILIKE ANY($2)
                        OR tags && $3::varchar[]
                        OR named_entities && $4::varchar[]
                      )
                    LIMIT 1
                """, 
                    cutoff, 
                    [f"%{k}%" for k in keywords], # ILIKE ANY mapping
                    keywords,                     # tags && array
                    keywords                      # named_entities && array
                )
                
                if rows: 
                    matched.append(signal) 
            except Exception as e:
                logger.debug(f"Signal match error: {e}")
 
        return matched
    
    async def _fetch_active_scenarios(self) -> List[Dict]:
        try:
            return await self._db.query("""
                SELECT scenario_id, headline, status, confidence_overall,
                       hypotheses, created_at, updated_at
                FROM scenarios
                WHERE status IN ('hypothesis', 'developing')
                  AND created_at > NOW() - INTERVAL '30 days'
                ORDER BY confidence_overall DESC
                LIMIT 100
            """)
        except Exception as e:
            logger.error(f"fetch_active_scenarios failed: {e}")
            return []
 
    async def _update_scenario(
        self,
        scenario_id:    str,
        new_confidence: int,
        new_status:     Optional[ScenarioStatus],
        notes:          str,
    ):
        # CODING CONVICTION: Audit Trails.
        # We append to a `confidence_history` JSONB array instead of just overwriting 
        # the confidence. This allows human analysts to trace exactly *when* and *why* 
        # an AI decided to upgrade or downgrade a scenario's likelihood.
        try:
            if new_status:
                await self._db.execute("""
                    UPDATE scenarios
                    SET confidence_overall = $1,
                        status            = $2,
                        updated_at        = NOW(),
                        confidence_history = confidence_history || $3::jsonb
                    WHERE scenario_id = $4
                """, 
                    new_confidence,
                    new_status.value,
                    f'[{{"ts":"{datetime.now(timezone.utc).isoformat()}",'
                    f'"confidence":{new_confidence},"notes":"{notes}"}}]',
                    scenario_id,
                )
            else:
                await self._db.execute("""
                    UPDATE scenarios
                    SET confidence_overall = $1,
                        status            = CASE
                            WHEN status = 'hypothesis' AND $2 >= 60 THEN 'developing'
                            ELSE status
                        END,
                        updated_at        = NOW(),
                        confidence_history = confidence_history || $3::jsonb
                    WHERE scenario_id = $4
                """, 
                    new_confidence,
                    new_confidence,
                    f'[{{"ts":"{datetime.now(timezone.utc).isoformat()}",'
                    f'"confidence":{new_confidence},"notes":"{notes}"}}]',
                    scenario_id,
                )
        except Exception as e:
            logger.error(f"update_scenario failed ({scenario_id}): {e}")
            